<div class="content-login">
    <div class="login-panel frm-panel">
        <form id="frm-login" method="POST" action="/login">
            <div class="frm-head">
                <h2><span></span>Ingresa a tu Cuenta</h2>
            </div>
            <div class="control-group">
                <label for="txtUsername" class="control-label">Username:</label>
                <div class="controls">
                    <input type="text" name="txtUsername" id="txtUsername" />
                </div>
            </div>
            <div class="control-group">
                <label for="txtPassword" class="control-label">Password:</label>
                <div class="controls">
                    <input type="password" name="txtPassword" id="txtPassword" />
                </div>
            </div>
            <div class="control-group last">
                <div class="control">
                    <button class="btn-admin">Ingresa</button>
                </div>
            </div>
        </form>
    </div>
</div>