<h3 class="admin-title">Solicitud de Portabilidad y Programación</h3>
 <?php $this->getMesseger();?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Solicitud de Portabilidad y Programación</h2>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>IdentificadorProceso</th>
                <th>CodigoCedente</th>
                <th>NumeracionSolicitada</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>