 <?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?> 
<wsdl:definitions targetNamespace="http://ws.inpac.telcordia.com" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:ns="http://ws.inpac.telcordia.com" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ttns="http://ws.inpac.telcordia.com" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
<wsdl:documentation>
		This is WSDL for MOCHE Web Service
	</wsdl:documentation>
  <wsdl:types>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://ws.inpac.telcordia.com">
			<xs:element name="receiveMessageRequest">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" name="userID" nillable="false" type="xs:string"/>
						<xs:element minOccurs="1" name="password" nillable="false" type="xs:string"/>
						<xs:element minOccurs="1" name="xmlMsg" nillable="false" type="xs:string"/>
						<xs:element minOccurs="0" name="attachedDoc" nillable="false" type="xs:base64Binary"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="receiveMessageResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" name="response" nillable="false" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
  </wsdl:types>
  <wsdl:message name="receiveMessageRequest">
    <wsdl:part name="parameters" element="ns:receiveMessageRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="receiveMessageResponse">
    <wsdl:part name="parameters" element="ns:receiveMessageResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ABDCPWebServicePortType">
    <wsdl:operation name="receiveMessage">
      <wsdl:input message="ns:receiveMessageRequest" wsaw:Action="urn:receiveMessageRequest">
    </wsdl:input>
      <wsdl:output message="ns:receiveMessageResponse" wsaw:Action="urn:receiveMessageResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ABDCPWebServiceSoap12Binding" type="ns:ABDCPWebServicePortType">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="receiveMessage">
      <soap12:operation soapAction="urn:receiveMessage" style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ABDCPWebService">
<wsdl:documentation>ABDCP Web service</wsdl:documentation>
    <wsdl:port name="ABDCPWebServiceHttpSoap12Endpoint" binding="ns:ABDCPWebServiceSoap12Binding">
      <soap12:address location="https://10.209.43.2/static/soap-service.php"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>