<h3 class="admin-title">(CP) Consulta Previa</h3>
 <?php $this->getMesseger();?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Consulta Previa</h2>
        <a class="btn-admin" title="Consultar Nuevo" href="/cp/new">Consultar Nuevo</a>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>IdentificadorProceso</th>
                <th>CodigoCedente</th>
                <th>NumeracionSolicitada</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>