<h3 class="admin-title">(ECPC) Consulta Previa al Cedente </h3>
 <?php $this->getMesseger();?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado Envío de Consulta Previa al Cedente</h2>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>IdentificadorProceso</th>
                <th>NumeroDocumentoIdentidad</th>
                <th>Numeracion</th>
                <th>TipoPortabilidad</th>
                <th>TipoServicio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
