<!doctype html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]> <html lang="es"> <![endif]-->
<?php echo $this->render("admin/head.phtml"); ?>
<body>
	<?php echo $this->layout()->content; ?>
	<?php echo $this->render("admin/footer.phtml"); ?>
        <script type="text/javascript">
            var yOSON ={
                "modulo":"<?php echo $this->module?>",
                "controller":"<?php echo $this->controller?>",
                "action":"<?php echo $this->action?>",
                "baseHost":"<?php echo SITE_URL?>",
                "statHost":"<?php echo STATIC_URL?>",
                "statVers":"?72f01fa",
                <?php foreach ($this->yosonVars as $key => $value) : 
                     echo '"'.$key.'":'.$value.', '; 
                    endforeach; 
                    echo '"min":"","AppCore":{},"AppSandbox":{},"AppSchema":{"modules":{},"requires":{}'
                    ?>  
                }
              };
        </script>
	<script src="<?php echo STATIC_URL?>js/libs/framework.js"></script>
	<script src="<?php echo STATIC_URL?>js/application/yoson.js"></script>
	<script src="<?php echo STATIC_URL?>js/modules/index.js"></script>
	<script src="<?php echo STATIC_URL?>js/application/schemas/modules.js"></script>
	<script src="<?php echo STATIC_URL?>js/application/appLoad.js"></script>
</body>
</html>