<h3 class="admin-title">Clientes</h3>
 <?php $this->getMesseger();?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Clientes</h2>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Teléfono</th>
                <th>Dni</th>
                <th>tipoPortabilidad</th>
                 <th>tipoServicio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>